language: ruby

rvm:
  - 2.1.1

bundler_args: '--without development'

env:
  global:
    - GIT_COMMITTER_NAME:  hanachin
    - GIT_COMMITTER_EMAIL: hanachin@gmail.com
    - GIT_AUTHOR_NAME:     hanachin
    - GIT_AUTHOR_EMAIL:    hanachin@gmail.com
    - secure: "KSymil+YkA5PhLtQxUhz3XqI1ezbs5LRk5m5LowP4oGmanzeettxTgNNdGnYDPIja/7IqOANEzPMshw7OPVVVaW85UbeOCT+n+PblsFOpjJR5NYhaxhi96crgy/Vwf5sYsUXITZkKwCirzuxy1C1NPyjF+2Fuhp1eWUC22F51/c="

script:
  - bundle exec jekyll build -d dist

after_success:
  - cd dist
  - echo "www.hanach.in" > CNAME
  - 'echo "rvm: 2.1.1" > .travis.yml'
  - git init
  - git add --all
  - 'git commit -m ":sparkles: Update from Travis CI :sparkles:"'
  - 'git push --quiet https://$GITHUB_TOKEN@github.com/hanachin/hanachin.github.io.git master -f 2> /dev/null'

branches:
  only:
    - source
